# Generated by Django 4.2.5 on 2023-11-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryMilestones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_gallery",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Titulo galeria"
                    ),
                ),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeria",
                "verbose_name_plural": "Galerias",
                "ordering": ["-datetime_creation"],
            },
        ),
        migrations.CreateModel(
            name="Milestones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Titulo hito"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="media/hito/", verbose_name="Imagen"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hito",
                "verbose_name_plural": "Hitos",
                "ordering": ["-datetime_creation"],
            },
        ),
        migrations.CreateModel(
            name="LinksMilestones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_link",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Titulo link"
                    ),
                ),
                ("link", models.URLField(max_length=255, verbose_name="Link")),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
                (
                    "name_milestones",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hitos.milestones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
                "ordering": ["-datetime_creation"],
            },
        ),
        migrations.CreateModel(
            name="ImgGalleryMilestones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_only",
                    models.ImageField(
                        upload_to="media/galeriahitos/", verbose_name="Imagen"
                    ),
                ),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hitos.gallerymilestones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen galeria",
                "verbose_name_plural": "Imagenes galerias",
                "ordering": ["-datetime_creation"],
            },
        ),
        migrations.AddField(
            model_name="gallerymilestones",
            name="milestones",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hitos.milestones"
            ),
        ),
    ]
