# Generated by Django 4.2.5 on 2023-09-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryTheaterPlays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_gallery",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Titulo galeria"
                    ),
                ),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
            ],
            options={"verbose_name": "Galeria", "verbose_name_plural": "Galerias",},
        ),
        migrations.CreateModel(
            name="TheaterPlays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Titulo Obra"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="media/obra/", verbose_name="Imagen"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
            ],
            options={"verbose_name": "Obra", "verbose_name_plural": "Obras",},
        ),
        migrations.CreateModel(
            name="LinksTheaterPlays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_link",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Titulo link"
                    ),
                ),
                ("link", models.URLField(max_length=255, verbose_name="Link")),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
                (
                    "name_theaterplays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.theaterplays",
                    ),
                ),
            ],
            options={"verbose_name": "Link", "verbose_name_plural": "Links",},
        ),
        migrations.CreateModel(
            name="ImgGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_only",
                    models.ImageField(
                        upload_to="media/galeria/", verbose_name="Imagen"
                    ),
                ),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.gallerytheaterplays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen galeria",
                "verbose_name_plural": "Imagenes galerias",
            },
        ),
        migrations.AddField(
            model_name="gallerytheaterplays",
            name="theaterplays",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.theaterplays"
            ),
        ),
    ]
