# Generated by Django 4.2.5 on 2023-09-19 13:33

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titulo")),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "image_news",
                    models.ImageField(
                        upload_to=apps.news.models.news_directory_path,
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "video_news",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.news.models.news_directory_path,
                        verbose_name="Video",
                    ),
                ),
                (
                    "link_news",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Link"
                    ),
                ),
                (
                    "datetime_creation",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creación"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha modificación"
                    ),
                ),
            ],
        ),
    ]
