# Generated by Django 4.2.5 on 2023-09-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="news", options={"verbose_name": "Noticia"},),
    ]
