# Generated by Django 4.2.5 on 2023-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-datetime_creation"], "verbose_name": "Noticia"},
        ),
        migrations.AddField(
            model_name="news",
            name="date_creation",
            field=models.DateField(auto_now=True, verbose_name="Fecha noticia"),
        ),
        migrations.AddField(
            model_name="news",
            name="head_news",
            field=models.TextField(default=False, verbose_name="Encabezado"),
        ),
    ]
