# Generated by Django 4.2.5 on 2023-09-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="schedules",
            field=models.TextField(blank=True, null=True, verbose_name="Horarios"),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="price",
            field=models.CharField(max_length=100, verbose_name="Valores"),
        ),
    ]
