# Generated by Django 4.2.5 on 2023-10-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Red social")),
                ("url", models.URLField(verbose_name="Enlace")),
                (
                    "img",
                    models.ImageField(
                        upload_to="media/contact/", verbose_name="Icono link"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enlace",
                "verbose_name_plural": "enlaces",
                "ordering": ["name"],
            },
        ),
    ]
